name: Main Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency: ci-${{ github.ref }}

jobs:
  info:
    uses: ./.github/workflows/call-info.yml

  deploy:
    needs: info
    runs-on: ubuntu-latest
    steps:
      # Checkout to repository
      - name: Checkout to repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build Vite Project
        env:
          BASE_URL: ${{ needs.info.outputs.baseUrl }}/
        working-directory: .
        run: |
          npm ci
          npm run build
        shell: bash

      - name: Main Deploy
        id: main-deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: gh-pages
          clean-exclude: pr-preview
